<?php
//3.1.1 - NotwwwDir
//3.1.3 - VirtualHostPortNone
//3.1.4 - txtTLDdev
//3.1.9 - VirtualHostName modified - Accept diacritical characters (IDN)
$langues = array(
    'langue' => '简体中文',
    'locale' => 'chinese',
    'addVirtual' => '添加虚拟主机',
    'backHome' => '返回首页',
    'VirtualSubMenuOn' => '必须将 <code>Wampmanager右键菜单</code> - <code>Wamp设置</code> - <code>显示虚拟主机菜单</code> 勾选上，然后重新加载本页面才能正常使用',
    'UncommentInclude' => '取消 %s 文件 <code>#Include conf/extra/httpd-vhosts.conf</code> 内容的注释 <small>(删除 # 符号)</small>',
    'FileNotExists' => '文件 <code>%s</code> 不存在',
    'txtTLDdev' => '主机名 %s 使用了 %s 顶级域，该顶级域被浏览器做了强制策略，不适合用来本地使用！请使用其它顶级域，例如：.test',
    'FileNotWritable' => '文件 <code>%s</code> 无法写入',
    'DirNotExists' => '<code>%s</code> 不存在或不是文件夹',
    'NotwwwDir' => '<code>%s</code> 文件夹已保留给<code>localhost</code>，请使用其它文件夹！',
    'NotCleaned' => '<code>%s</code> 文件尚未清理，里面还包含一些虚拟主机配置示例，例如: dummy-host.example.com',
    'NoVirtualHost' => '<code>%s</code> 文件中没有定义虚拟主机<br/>它至少应该定义一个<code>localhost</code>的虚拟主机',
    'NoFirst' => '<code>%s</code> 文件里的第一个虚拟站点必须是 <code>localhost</code>',
    'ServerNameInvalid' => '无效主机名：<code>%s</code>',
    'LocalIpInvalid' => '无效本地IP：<code>%s</code>',
    'VirtualHostName' => '<code>主机名</code> 不能有空格或下划线(_) ',
    'VirtualHostFolder' => '虚拟主机站点目录（必须是完整的绝对路径）<i>示例: <code>C:/wamp/www/projet/</code> 或 <code>E:/www/site1/</code></i> ',
    'VirtualHostIP' => '如果你要通过其它本地IP使用虚拟主机，那么请输入要使用的本地IP(127.x.y.z)',
    'VirtualHostPort' => '如果你要使用默认以外的端口，请在下方勾选并选择要使用的端口。可选端口：%s',
    'VirtualHostPortNone' => '如果你想监听(<code>Listen port</code>)默认端口以外的端口，则必须通过右键单击右下角任务栏的Wampserver的图标，然后选择 <code>工具</code> -&gt; <code>新增Apache监听端口</code> 来添加你想监听的端口',
    'VirtualAlreadyExist' => '填写的域名 <code>%s</code> 已存在',
    'VirtualIpAlreadyUsed' => '本地IP <code>%s</code> 已存在',
    'VirtualPortNotExist' => '填写的 <code>%s</code> 端口未在Apache里监听 <code>"Listen port"</code>',
    'VirtualPortExist' => '<code>%s</code> 端口是默认监听的端口，它不应该包含在输入的内容里',
    'VirtualHostExists' => '已添加的虚拟主机:',
    'Start' => '开始创建虚拟主机(可能需要等待一些时间...)',
    'GreenErrors' => '绿色框的错误可以自动纠正',
    'Correct' => '开始自动校正绿色边框面板内的错误',
    'NoModify' => '无法修改 <code>httpd-vhosts.conf</code> 或 <code>hosts</code> 文件',
    'VirtualCreated' => '文件已修改。虚拟主机<code>%s</code>已创建',
    'CommandMessage' => '更新 DNS 提示:',
    'However' => '如果主机名无法正常使用，您可以尝试以下操作。<br>右键单击 <code>Wampmanager 图标</code> - <code>工具</code> - <code>重启DNS</code><br> <i>(以上步骤都需要您手动操作)</i>',
    'suppForm' => '显示删除虚拟主机',
    'suppVhost' => '删除虚拟主机',
    'Required' => '必填',
    'Optional' => '选填',
);