<?php
//3.1.1 - NotwwwDir
//3.1.3 - VirtualHostPortNone
//3.1.4 - txtTLDdev
//3.1.9 - VirtualHostName modified - Accept diacritical characters (IDN)
$langues = array(
    'langue' => '简体中文',
    'locale' => 'chinese',
    'addVirtual' => '添加虚拟主机',
    'backHome' => '返回首页',
    'VirtualSubMenuOn' => 'The <code>VirtualHost sub-menu</code> item must be set to (On) in the <code>Wamp Settings</code> Right-Click menu. Then reload this page',
    'UncommentInclude' => 'Uncomment <small>(Suppress #)</small> the line <code>#Include conf/extra/httpd-vhosts.conf</code><br>in file %s',
    'FileNotExists' => 'The file <code>%s</code> does not exists',
    'txtTLDdev' => 'The ServerName %s use TLD %s which is monopolized by web browsers. Use another TLD (.test for example)',
    'FileNotWritable' => 'The file <code>%s</code> is not writable',
    'DirNotExists' => '<code>%s</code> does not exists or is not a directory',
    'NotwwwDir' => 'The <code>%s</code> folder is reserved for "localhost". Please use another folder.',
    'NotCleaned' => 'The <code>%s</code> file has not been cleaned.<br>There remain VirtualHost examples like: dummy-host.example.com',
    'NoVirtualHost' => 'There is no VirtualHost defined in <code>%s</code><br>It should at least have the VirtualHost for localhost.',
    'NoFirst' => 'The first VirtualHost must be <code>localhost</code> in <code>%s</code> file',
    'ServerNameInvalid' => 'The ServerName <code>%s</code> is invalid.',
    'LocalIpInvalid' => 'The local IP <code>%s</code> is invalid.',
    'VirtualHostName' => 'Name of the <code>Virtual Host</code> No space - No underscore(_) ',
    'VirtualHostFolder' => '虚拟主机站点目录（必须是完整的绝对路径）<i>示例: <code>C:/wamp/www/projet/</code> 或 <code>E:/www/site1/</code></i> ',
    'VirtualHostIP' => '<code class="option">If</code> you want to use VirtualHost by IP: <code class="option">local IP</code> 127.x.y.z ',
    'VirtualHostPort' => '<code class="option">If</code> you want to use "Listen port" other than the default <code class="option">Accepted ports</code> %s',
    'VirtualHostPortNone' => '如果你想监听(<code>Listen port</code>)默认端口以外的端口，则必须通过右键单击右下角任务栏的Wampserver的图标，然后选择 <code>Tools</code> -&gt; <code>Add a Listen port for Apache</code> 来添加你想监听的端口',
    'VirtualAlreadyExist' => '填写的域名 <code>%s</code> 已存在',
    'VirtualIpAlreadyUsed' => 'The local IP <code>%s</code> already exists',
    'VirtualPortNotExist' => '填写的 <code>%s</code> 端口未在Apache里监听 <code>"Listen port"</code>',
    'VirtualPortExist' => 'The port <code>%s</code> is default "Listen port" Apache and should not be mentioned',
    'VirtualHostExists' => '已添加的虚拟主机:',
    'Start' => 'Start the creation of the VirtualHost (May take a while...)',
    'GreenErrors' => 'The green framed errors can be corrected automatically.',
    'Correct' => 'Start the automatic correction of errors inside the green borders panel',
    'NoModify' => 'Impossible to modify <code>httpd-vhosts.conf</code> or <code>hosts</code> files',
    'VirtualCreated' => 'The files have been modified. Virtual host <code>%s</code> was created',
    'CommandMessage' => 'Messages from the console to update DNS:',
    'However' => 'You may add another VirtualHost by validate "Add a VirtualHost".<br>However, for these new VirtualHost are taken into account by Apache, you must run item<br><code>Restart DNS</code><br>from Right-Click Tools menu of Wampmanager icon. <i>(This can unfortunately not be done automatically)</i>',
    'suppForm' => '显示删除虚拟主机',
    'suppVhost' => '删除虚拟主机',
    'Required' => '必填',
    'Optional' => '选填',
    );
