<?php
// 3.2.0 - txtProjects
//

defined('WAMPSERVER_ROOT') or define('WAMPSERVER_ROOT', str_replace('\\', '/', dirname(dirname(__DIR__))));

$langues = array(
	'langue' => 'English',
	'locale' => 'english',
	'titreHtml' => 'WAMPSERVER主页',
	'titreConf' => '服务器配置',
	'versa' => 'Apache 版本：',
	'doca2.2' => 'httpd.apache.org/docs/2.2/zh-cn/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/zh-cn/',
	'versp' => 'PHP 版本：',
	'server' => '服务器软件：',
	'documentation' => '文档',
	'docp' => 'www.php.net/manual/zh/',
	'versm' => 'MySQL 版本：',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'MariaDB 版本：',
	'docmaria' => 'mariadb.com/kb/zh-cn/mariadb-documentation/',
	'phpExt' => 'PHP已加载扩展：',
	'titrePage' => '工具',
	'txtProjet' => '你的项目',
	'txtNoProjet' => '尚无项目<br/>如果想创建项目，可以在“' . WAMPSERVER_ROOT . '/www”目录下创建一个文件夹',
	'txtProjects' => '这些都是“%s”目录下的文件夹。<br />如果你想通过域名直接访问这些文件夹，你需要将这些文件夹在“httpd-vhost.conf”里将它们定义为虚拟主机',
	'txtAlias' => '你的别名',
	'txtNoAlias' => '尚无别名<br />如果想创建别名，可以在“' . WAMPSERVER_ROOT . '/alias”目录下创建',
	'txtVhost' => '你的虚拟主机',
	'txtServerName' => 'The ServerName %s has syntax error in file %s',
	'txtDocRoot' => 'The ServerName %s use DocumentRoot %s reserved to localhost',
	'txtTLDdev' => 'The ServerName %s use TLD %s which is monopolized by web browsers. Use another TLD (.test for example)',
	'txtServerNameIp' => 'IP %s for Servername %s is not valid in file %s',
	'txtVhostNotClean' => 'The %s file has not been cleaned. There remain VirtualHost examples like: dummy-host.example.com',
	'txtNoVhost' => 'No VirtualHost yet. Add one for each project in the file: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Uncomment or add <i>Include conf/extra/httpd-vhosts.conf</i> in file wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => '文件“ %s ”不存在',
	'txtNoPath' => '路径%s不存在，定义自%s（文件：%s）',
	'txtNotWritable' => 'The file: %s is not writable',
	'txtNbNotEqual' => 'The number of %s does not match the number of %s in %s file',
	'txtAddVhost' => '添加一个虚拟主机',
	'txtPortNumber' => 'Port number for %s has not correct value or is not the same in file %s',
	'txtCorrected' => 'Some VirtualHosts errors can be corrected.',
	'forum' => 'Wampserver 论坛',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Apache 端口：',
	'mysqlportUsed' => 'MySQL 端口：',
	'mariaportUsed' => 'MariaDB 端口：',
	'nolocalhost' => 'It\'s a bad idea to add localhost in the url of launching projects. It is best to define VirtualHost in<br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br />file and not add localhost in the url.',
	);
